### ISSUE TITLE
About evaluation code

### ISSUE THREAD

**Issue by Junwen-Huang** [jin-s13/COCO-WholeBody#1]
In `myeval_righthand.py`, I find this line [L165](https://github.com/jin-s13/COCO-WholeBody/blob/master/evaluation/myeval_righthand.py#L165), which multipies `sigmas` with 2. However, there is no similar process [here](https://github.com/jin-s13/COCO-WholeBody/blob/master/evaluation/myeval_lefthand.py#L166) in `myeval_lefthand.py`. Is it a mistake?

**Comment by jin-s13** [comment]
Thank you for reporting this typo. We have fixed it.
