### ISSUE TITLE
Is there any plan to open zoomnet implementation details?

### ISSUE THREAD

**Issue by zhouwei5113** [jin-s13/COCO-WholeBody#10]

**Comment by jin-s13** [comment]
Thanks for your interest in our work. We plan to release the implementation of ZoomNet in [MMPose](https://github.com/open-mmlab/mmpose) soon. Are there any specific questions about the implementation?

**Comment by wangtss** [comment]
> Thanks for your interest in our work. We plan to release the implementation of ZoomNet in [MMPose](https://github.com/open-mmlab/mmpose) soon. Are there any specific questions about the implementation?

I'm also interested in the ZoomNet, could you please tell me what kind of backbone you use in the FeatureNet part?

**Comment by jin-s13** [comment]
The FeatureNet and the BodyNet together form a HRNet-w32 network.
FeatureNet is the stem of HRNet, with {conv1+bn+conv2+bn} structure. And BodyNet is the rest of HRNet.

**Comment by wangtss** [comment]
> The FeatureNet and the BodyNet together form a HRNet-w32 network.
> FeatureNet is the stem of HRNet, with {conv1+bn+conv2+bn} structure. And BodyNet is the rest of HRNet.

Thanks for the quick reply, helps a lot!

**Comment by YangYangGirl** [comment]
![image](https://user-images.githubusercontent.com/32426369/103753307-da473f80-5045-11eb-8ba5-86c1de9cfe24.png)
Thanks for your nice work. I wonder how did you distinguish between the left and right hand? As the images below show, the inconsistencies in orientation make it difficult for the model to make a judgment.

![image](https://user-images.githubusercontent.com/32426369/103761275-5e52f480-5051-11eb-82b2-7d543baff2e2.png)
![image](https://user-images.githubusercontent.com/32426369/103761351-7fb3e080-5051-11eb-8047-400b444034c4.png)
![image](https://user-images.githubusercontent.com/32426369/103761470-ad992500-5051-11eb-9d1b-e2fd8398c331.png)

**Comment by jin-s13** [comment]
@YangYangGirl  For FasterRCNN, we simply treat face, lefthand, and righthand as three different types of objects.
Since the receptive field is large enough, we can get reasonable results.

**Comment by liangwx** [comment]
mmpose中关于wholebody部分的算法中似乎没有找到zoomnet的train code,请问能提供一下zoomnet的train code的链接吗 @jin-s13
