### ISSUE TITLE
Foot keypoint sigmas

### ISSUE THREAD

**Issue by DuncanZauss** [jin-s13/COCO-WholeBody#11]
Hello!
Thank you for making this nice work available.
In [myeval_foot.py](https://github.com/jin-s13/COCO-WholeBody/blob/bce41c77f51e24670de7f22d06c2ea9b4852ab35/evaluation/myeval_foot.py#L163), line 163 you use the following sigmas:
`sigmas = np.array([0.68, 0.66, 0.66, 0.92, 0.94, 0.94]) / 10.0`
So you are using different sigmas for the left and right foot. Could you let me know, why this is the case?
All the other sigmas are symmetrical, so that the corresponding left and right body parts have the same sigma.
Best,
Duncan

**Comment by jin-s13** [comment]
The sigmas are calculated individually/separately for each keypoint. So it is possible that some symmetric parts have different sigmas. 
For the face keypoints, the sigmas are not symmetric either. 
For hand keypoints, we treat the left and the right hands equally (for model design, and evaluation). So we specially average the sigmas for left/right hands. 
For body keypoints, we directly use the sigmas provided by the MSCOCO team.

**Comment by nomaad42** [comment]
> The sigmas are calculated individually/separately for each keypoint. So it is possible that some symmetric parts have different sigmas. For the face keypoints, the sigmas are not symmetric either. For hand keypoints, we treat the left and the right hands equally (for model design, and evaluation). So we specially average the sigmas for left/right hands. For body keypoints, we directly use the sigmas provided by the MSCOCO team.

How do you calculate the sigmas for the each keypoint?
