### ISSUE TITLE
How do I run the code on new images?

### ISSUE THREAD

**Issue by Anirudh257** [jin-s13/COCO-WholeBody#2]
Thanks for releasing the code to your great work. I want to generate Coco-JSON files for my own images. Can you provide the steps to do the same?

**Comment by jin-s13** [comment]
Hi, COCO-WholeBody json file is mostly manually annotated. For more details about the annotation procedure, please refer to our [paper.](https://arxiv.org/abs/2007.11858)

**Comment by Anirudh257** [comment]
Thanks for the clarification.
