### ISSUE TITLE
COCO-Wholebody dataset with detection networks

### ISSUE THREAD

**Issue by mfarenzena** [jin-s13/COCO-WholeBody#20]
Hi, 

I read in the additional material of your ECCV paper that you compared Zoomnet results with face and hand bounding box detection from Faster-RCNN. I was wandering if you ever tried Faster-RCNN on the whole dataset or you tried other detection networks. 

Thanks.

**Comment by jin-s13** [comment]
Yes. Please see the paper for more information.
![image](https://user-images.githubusercontent.com/11788150/116638523-173e9580-a999-11eb-8de3-ce907198f2ba.png)
