### ISSUE TITLE
tensorflow implementation

### ISSUE THREAD

**Issue by soans1994** [jin-s13/COCO-WholeBody#21]
hello author,

thank you for the full body dataset. can this dataset be used to train a model with tensorflow? will it slow down the realtime performance in terms of fps?

thank you

**Comment by jin-s13** [comment]
I have not used tensorflow before, but I think it would be easy to train the model using tensorflow.

**Comment by soans1994** [comment]
thank you. which framework did you use for implementation.

**Comment by jin-s13** [comment]
We use pytorch for implementation, the [MMPose](https://github.com/open-mmlab/mmpose) codebase. Please check it.

**Comment by soans1994** [comment]
thank you. i will check it

**Comment by soans1994** [comment]
while creating the whole body annotations for coco dataset, did you use landmark keypoint face detection model to extract the facial points? or did you manual annotation. and what about the foot annotations.

**Comment by jin-s13** [comment]
For face/hand keypoints, we first use models pre-trained on a collection of different datasets to obtain psudo-labels, then we manually correct the mislabeled keypoints.
For foot keypoints, we directly manually label the keypoints.
More details can be found in the paper.

**Comment by soans1994** [comment]
thank you very much for your response

**Comment by soans1994** [comment]
@jin-s13  
i have some doubts regarding face keypoints. can you please look into it.
https://github.com/jin-s13/COCO-WholeBody/issues/22

thank you

**Comment by soans1994** [comment]
hello again,

when i use the face keypoints from whole body json, i get some error for a sample in between, like 
SystemError: tile cannot extend outside image
Is there some problem with the bbox values? Other works good all 68 landmarks.
did any other people get similar error.

Thank you
