### ISSUE TITLE
face keypoints versus body keypoints

### ISSUE THREAD

**Issue by soans1994** [jin-s13/COCO-WholeBody#22]
hello again author,

i have some querry regarding the face keypoints implementation.

i hope you know the popular openpose and tfpose implementation for pose detection. when i test those models caffe or tensorflow, it takes the occluded parts into consideration (for example, if i cover my eyes with the hands, the model wont detect my eyes). but, when i use the facial landmarks model, it tries to detect all the keypoints and best match the face. Is it because of the type of dataset? (the coco dataset takes the occlusions into consideration) and the (68 facial landmarks dataset doesn't).

Am i correct? when i implement the model with your whole body dataset, all the facial keypoints will be detected even if the facial points are missing right? or even for the side face angles, it still detects the ears and jaw line on the other side of the face.

sorry for my noob question
thank you

**Comment by jin-s13** [comment]
1. The annotation protocols (especially how to handle occluded keypoints) of different datasets are different. COCO dataset has a visibility label for each keypoint (0 for missing, 1 for occlusion, and 2 for visible). But some datasets will ignore the visibility label, and try to guess the most possible location for these occluded keypoints. 
2. For face keypoint dataset annotation, there are generally two popular ways to annotate the occluded face keypoints. The first one is to annotate the occluded keypoints by guessing its location (just like you can see through the occlusion). The second one is to annotate the occluded keypoints on the nearest visible face **boundary** (the occluded jaw line will appear on the nose-mouse boundary). Our COCO-Wholebody dataset follows the second annotation protocol for face keypoint annotation.
3. The pose model will also produce a confidence score for each keypoint. And the occluded keypoints often have lower confidence score. You may use a threshold to filter out these keypoints.

**Comment by soans1994** [comment]
@jin-s13 

thank you for the clear explaination. i understand now that the face keypoints are annoted to nearest visible face points, unlike the coco human pose annotation. 

Regards
