### ISSUE TITLE
COCO dataset - head boxes

### ISSUE THREAD

**Issue by cilic-mile** [jin-s13/COCO-WholeBody#23]
Hi, in the readme file you outlined some popular datasets and the annotations each of them provides.
For [COCO 2014 dataset](https://cocodataset.org/#download) you checked that head box is available. However, I cannot find head boxes in their annotations. It only contains 80 categories (none of them is head) and 17 person keypoints.
Am I looking at the wrong place or is it a mistake in the readme file?

**Comment by cilic-mile** [comment]
Just found it in the DensePose annotations. Thank you anyway :)

**Comment by tino926** [comment]
@cilic-mile , 
Hi, I am also looking for the head box annotation, but I can't find that in DensePose annotation (densepose_coco_2014_train.json). Could you share how you get the head box?

**Comment by cilic-mile** [comment]
Hi @tino926 , there are no head box annotations, there are only head points.
I just took the top-left and bottom-right points to generate head box. You can then expand the box if it is too small

I wasn't too happy with the results since DensePose does not have annotations for all heads
