### ISSUE TITLE
how to get multi person heatmaps/confidence maps

### ISSUE THREAD

**Issue by soans1994** [jin-s13/COCO-WholeBody#24]
hello authors,

Sorry i want to ask a question related to Multi-person detection.
I want to ask wheter the COCO person dataset is specialized for multi-person?
i have trained a simple model using FCN for face keypoint regression. Can you please tell me how we can get heatmaps of muliple faces in the bottom-up approach. My current model takes input of 96x96x1 image and gives 96x96x15 size heatmaps for 15 keypoints. I trained my model using datset consisting of images with single face. Do i need the datset with multiple faces? and do I need bouding box information or mask information too?

Please give me your advice
thank you

**Comment by jin-s13** [comment]
1. Yes, COCO person dataset is for multi-person pose estimation.
2. If you are using bottom-up approach, I think a dataset with multiple faces is necessary. You may simply use coco-wholebody dataset.
