### ISSUE TITLE
Tagging wholebody

### ISSUE THREAD

**Issue by ignacio-ferreira-dev** [jin-s13/COCO-WholeBody#26]
Hi, is there any tagging tool that supports the coco whole-body format?
We want to generate a dataset using this format for a use case, but we can't find any good tagger.
Any additional advice related to generating labels and then fixing them is also welcome.
Thanks!

**Comment by jin-s13** [comment]
You may try [labelbee](https://github.com/open-mmlab/labelbee-client).

**Comment by ignacio-ferreira-dev** [comment]
Will take a look, thanks!
