### ISSUE TITLE
Matching of foot keypoints to each body parts

### ISSUE THREAD

**Issue by maketo97** [jin-s13/COCO-WholeBody#27]
@jin-s13 @Fang-Haoshu @Canwang-sjtu @luminxu Hi, first at all, thanks in open sourcing the coco whole body annotations. I have searched through Google and found the matching of actual body parts to coco 'keypoints': [x1,y1,v1,...,xk,yk,vk] (k=17).
['Nose', 'Leye', 'Reye', 'Lear', 'Rear', 'Lsho', 'Rsho', 'Relb', 'Lwri', 'Rwri', 'Lhip', 'Rhip', 'Lkne', 'Rkne', 'Lank', 'Rank']

However, I cannot find the matching list for foot keypoints. Could you tell me which body part matches to each coco 'foot kpts'? Looking forward to your reply. Thanks in advance.

**Comment by jin-s13** [comment]
Please check https://github.com/jin-s13/COCO-WholeBody/blob/master/data_format.md

**Comment by maketo97** [comment]
Thanks for reply.

https://github.com/jin-s13/COCO-WholeBody/blob/master/imgs/Fig2_anno.png
In the bottom left of the image, keypoints 18, 19, 20 are for the left feet while keypoints 21, 22, 23 are for the right feet?

**Comment by jin-s13** [comment]
Yes.

**Comment by maketo97** [comment]
Ok, thanks 👌🏻
