### ISSUE TITLE
WholeBody-Hand (WBH)   Where？

### ISSUE THREAD

**Issue by mywordwin** [jin-s13/COCO-WholeBody#28]
Hey bro, is WBH a separate dataset cropped from the COCO-WholeBody and if so where can I get it. Wish you the best at work!

**Comment by jin-s13** [comment]
Hi, we did not separately cropped the hand. Instead we directly load the original annotation file. 
see https://github.com/open-mmlab/mmpose/blob/master/mmpose/datasets/datasets/hand/hand_coco_wholebody_dataset.py

**Comment by mywordwin** [comment]
> 嗨，我们没有单独裁剪手。相反，我们直接加载原始注释文件。 见https://github.com/open-mmlab/mmpose/blob/master/mmpose/datasets/datasets/hand/hand_coco_wholebody_dataset.py

Thank you for your prompt reply and wish you a happy day!
