### ISSUE TITLE
Is there a trained model I can use directly?

### ISSUE THREAD

**Issue by abhaydoke09** [jin-s13/COCO-WholeBody#3]

**Comment by jin-s13** [comment]
Thanks for your interest in our work!
We plan to support COCO-WholeBody in our newly released code-base [MMPose](https://github.com/open-mmlab/mmpose) this month (Sep, 2020), see [Iteration Plan](https://github.com/open-mmlab/mmpose/issues/118).

**Comment by jin-s13** [comment]
Hi, we have supported COCO-WholeBody in MMPose.
We also provide a much stronger pre-trained model based on [HRNet-W48+DARK](https://github.com/open-mmlab/mmpose/tree/master/configs/top_down/darkpose).
Please try this.
