### ISSUE TITLE
Qestion about  the feet annotation！

### ISSUE THREAD

**Issue by 2050airobert** [jin-s13/COCO-WholeBody#31]
pass

**Comment by 2050airobert** [comment]
hi， 
     请问下，具体标注的时候，对于脚部的三个点是完全人工标注的，标注的实际操作中具体的大脚趾和小脚趾是如何找到具体的点的，尤其是coco 大部分图片都是穿鞋的情况，这个要找大脚趾更是难上加难，具体咱们如何保证标注点的准确性和高质量结果呢？ 是否有什么措施，或者具体的标注规则是？
    期待您的回答 

BR

**Comment by jin-s13** [comment]
1. 没有特别具体的规则，要求标注员脑补猜测大拇指和小拇指的位置。
2. 这个是模型预测的结果，而不是人工gt标注的结果。大拇指和小拇指不太容易区分，模型的精度不够高，没有区分出来。

**Comment by 2050airobert** [comment]
pass

**Comment by jin-s13** [comment]
1. _gt人员需要根据预测的大拇指和小拇指的位置，然后进一步改进调整更准确的位置_
gt是完全人工标注的。没有预测+改进。
2. _其实我关注的是脚部的三个点，大脚趾和小脚趾如何标注的？ 如何让标注人员能更准确的标注出来？_
如果是侧面，其实大脚趾和小脚趾不太容易区分。如果是正面，其实还蛮明显。
3. _你看我上面的这张图，明显只画出了脚跟和脚前部的一个点，而实际上标注的数据应该是脚部有三个点啊？这脚前部的点是用什么公式算出来的？_
其实脚的前部是两个点，只不过两个点非常接近，看上去好像是一个点。这是因为，这个模型脚部点没学好，两个点预测到了一起去。。

**Comment by 2050airobert** [comment]
pass

**Comment by jin-s13** [comment]
恩，模型没区分好吧。

**Comment by jin-s13** [comment]
![image](https://user-images.githubusercontent.com/11788150/185117113-53a78e9f-6894-4f99-acab-7e05f049b098.png)

主页这张图，是我们标注的效果的示例。

**Comment by 2050airobert** [comment]
pass

**Comment by 2050airobert** [comment]
pass

**Comment by jin-s13** [comment]
可以看看这两个讨论

https://github.com/open-mmlab/mmpose/issues/921

https://github.com/open-mmlab/mmpose/issues/822

**Comment by 2050airobert** [comment]
pass

**Comment by jin-s13** [comment]
1. _脚部点不仅可以检测出来而且不会出现交叉的现象，对吗？_
好像是的。
2. _到底什么模型可以把脚部标注的这两个点能区分开呢？_
不清楚。有些模型可以，有些模型不可以。可以尝试加强一下，两个脚趾点的权重，可能会有帮助。

**Comment by 2050airobert** [comment]
pass

**Comment by jin-s13** [comment]
哈哈，你说的也有道理。
我们感觉模型应该还是有希望可以区分的。之所以标了两个点，标两个点可以区分左右，是有一些实用价值的。
现在的模型不太容易区分，不意味着这个问题就没法做。我想后续可以仔细研究一下这个问题，看看能不能解决这个问题，搞一个更好的模型。

**Comment by 2050airobert** [comment]
pass
