### ISSUE TITLE
zoomNAS  missing!

### ISSUE THREAD

**Issue by 2050airobert** [jin-s13/COCO-WholeBody#34]
hi，
    请问下这个zoomNAS zoomnet 模型以及训练代码 何时可以发布呢? 
[ZoomNAS: Searching for Whole-body Human Pose Estimation in the Wild"](https://ieeexplore.ieee.org/document/9852279)
BR

**Comment by jin-s13** [comment]
Thanks for your interest in our work. We are still working on refactoring the codes. Please stay tuned. Thank you for your patience.

**Comment by 2050airobert** [comment]
it will be release at next month or octorber probably ?

**Comment by jin-s13** [comment]
@luminxu  How do you think?  
Let's work on it! Hope it will not take too much time.

**Comment by luminxu** [comment]
OK, we will work on it these months.

**Comment by 2050airobert** [comment]
@luminxu @jin-s13 
Maybe it is related with "Pose-for-Everything" which could be summarized as a good report or  open source release. 
Looking forwad to your  amazing work about zoomnet with coco wholebody datasets.
BR

**Comment by danigarciaoca** [comment]
Hi! Did ZoomNAS get released?

**Comment by shuishiwojiade** [comment]
Three years later：Did ZoomNAS get released?
