### ISSUE TITLE
wholebody json foot_kpts顺序问题！

### ISSUE THREAD

**Issue by 2050airobert** [jin-s13/COCO-WholeBody#37]
你好，
      请问下几个问题:
   1 在coco_wholebody_XXX_v1.0.json 里面  "foot_kpts" 里面 坐标点的顺序是"大脚趾 18  小脚趾 19  足跟 20    右脚:  大脚趾 21 小脚趾 22  足跟 23 "吗？  还是其他顺序 比如"右脚：足跟 20 大脚趾 18  小脚趾 19      左脚 ：   足跟 23  大脚趾 21 小脚趾 22   "
 "foot_kpts": [
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0
            ]
![image](https://user-images.githubusercontent.com/8407513/197121549-e0ce2064-f0a5-454a-a2ec-353b133d3d02.png)
  2  "lefthand_kpts" "righthand_kpts" "face_kpts" 在json里面保存的坐标点顺序 都是按照如下图 标号从小到大排列的吗？
![image](https://user-images.githubusercontent.com/8407513/197122477-6915c646-bbfd-4e63-8a9d-681c12372b34.png)
   期待您的答复，多谢
BR

**Comment by jin-s13** [comment]
跟图片一样的
