### ISSUE TITLE
Whole Hand AP

### ISSUE THREAD

**Issue by mywordwin** [jin-s13/COCO-WholeBody#38]
Hey bro,I got the AP and AR of the left and right hands respectively, so how do I get the AP and AR of the whole hand? like the evaluation results of other methods.
![image](https://user-images.githubusercontent.com/39481420/199180825-ac81448b-d9aa-485f-8f30-a592d698f70a.png)

**Comment by jin-s13** [comment]
Hi, we simply calculate their mean.

**Comment by mywordwin** [comment]
Got it bro, thanks for the prompt reply！
