### ISSUE TITLE
Annotation issue

### ISSUE THREAD

**Issue by ChilsonZhu** [jin-s13/COCO-WholeBody#39]
Thank you for sharing this wonderful project!

I just noticed that the visiability flags of lefthand and righthand keypointed are float numbers as the dict item shown below:

            "lefthand_kpts": [
                237.0,
                426.0,
                0.10405432432889938,
                245.0,
                428.0,
                0.20745894312858582,
                253.0,
                430.0,
                0.20745894312858582,
                261.0,
                433.0,
                0.5343613624572754,
                269.0,
                438.0,
                0.2143213450908661,
                265.0,
                429.0,
                0.12357126176357269....]

Why they are set in a different format insead of the orginal flags [0, 1, 2]?

**Comment by jin-s13** [comment]
Pls refer to https://github.com/jin-s13/COCO-WholeBody/blob/master/data_format.md
