### ISSUE TITLE
hrnet手部ap计算

### ISSUE THREAD

**Issue by mywordwin** [jin-s13/COCO-WholeBody#40]
![image](https://user-images.githubusercontent.com/39481420/203670822-9db83512-d42c-43c4-9378-cc074594cfe2.png)
你好，我知道了这个ap是左右手ap平均得到的，那我想问一下，左右手ap是一个模型测试出来的，还是左手一个模型，右手一个模型，分别测试再计算的？祝工作顺利！

**Comment by mywordwin** [comment]
@jin-s13 希望您百忙之中回答一下，谢谢。祝生活愉快！

**Comment by jin-s13** [comment]
这里的hrnet是一个133个点的模型，并非单手模型
