### ISSUE TITLE
I want to make a dataset in coco-wholebody format. What tool do you use to make it?

### ISSUE THREAD

**Issue by shopkeeper2020** [jin-s13/COCO-WholeBody#42]

**Comment by jin-s13** [comment]
I used internal labeling tool. You may try labelme.

**Comment by shopkeeper2020** [comment]
> I used internal labeling tool. You may try labelme.

Thanks for your prompt reply.And I want to know which attributes in the dataset are not necessary if they are only used for training?

**Comment by jin-s13** [comment]
Please refer to https://github.com/open-mmlab/mmpose/blob/master/docs/en/faq.md#data

**Comment by shopkeeper2020** [comment]
> Please refer to https://github.com/open-mmlab/mmpose/blob/master/docs/en/faq.md#data

Thanks for the quick reply！
