### ISSUE TITLE
Calculating Sigmas

### ISSUE THREAD

**Issue by nomaad42** [jin-s13/COCO-WholeBody#44]
Thank you very much for your repo!

How do you calculate the sigmas for each keypoint?

**Comment by jin-s13** [comment]
We ask 3 different annotators to annotate the same images, and calculate the standard deviation.
Please refer to our [paper](https://arxiv.org/pdf/2208.11547.pdf) for more details.

**Comment by nomaad42** [comment]
@jin-s13 

Thank you for your response!
