### ISSUE TITLE
Is the real annotation like this? (Including a large number of tiny-bounding boxes)

### ISSUE THREAD

**Issue by qingtianwu** [jin-s13/COCO-WholeBody#46]
Hello, thank you very much for your work. 

During the process of checking the training set, I found that the annotations contain many samples with tiny-boxes, and their key point information is lost. Is this reasonable?

As the picture shows, 
![train_batch1](https://github.com/jin-s13/COCO-WholeBody/assets/36837595/357891fa-1503-4362-9eea-4d9533c0e96d)

Should I filter out these samples with tiny boxes? Since the AP  from my trained model is very bad.

**Comment by jin-s13** [comment]
These are original annotations, we did not filter out them.
