### ISSUE TITLE
I am unable to download the whole body annotations from the train onedrive do you have an alternative link ?

### ISSUE THREAD

**Issue by grpinto** [jin-s13/COCO-WholeBody#47]

**Comment by Sierkinhane** [comment]
Hi, maybe you can download it from [google drive](https://drive.google.com/file/d/1thErEToRbmM9uLNi1JXXfOsaS5VK2FXf/view)

**Comment by ssifat9** [comment]
Do you have an alternative link of whole body annotations for the validation  onedrive?
onedrive link is not working

**Comment by jin-s13** [comment]
Alternatively, we also provide the BaiduPan download link.

BaiduPan Link: https://pan.baidu.com/s/19daDw9JeMlOnfNGZ2pB5Gw?pwd=pu6j

Password: pu6j
