### ISSUE TITLE
I am unable to download the whole body annotations 

### ISSUE THREAD

**Issue by ssifat9** [jin-s13/COCO-WholeBody#49]
Do you have an alternative link of whole body annotations for the validation onedrive?
onedrive link is not working

**Comment by jin-s13** [comment]
Hi, we have updated a BaiduPan link.
BaiduPan Link: https://pan.baidu.com/s/19daDw9JeMlOnfNGZ2pB5Gw?pwd=pu6j
pwd: pu6j
