### ISSUE TITLE
nice work, missing keypoints

### ISSUE THREAD

**Issue by ygwangthu** [jin-s13/COCO-WholeBody#6]
It is a nice work. 

However, I found that some clear images (e.g., 000000385029.jpg, 000000524456.jpg ) include hands, but keypoints labeling for those hands are missing. Will you update the labeling files in the future, or just let it go as it now?

**Comment by jin-s13** [comment]
Thank you for reporting this issue.
Yes. We will check the annotations again & add missing labels in the future. 
For convenience, we plan to keep the current version (v1.0) annotation files unchanged. The updated version will have a different suffix (for example, v2.0).
Thanks again.

**Comment by ygwangthu** [comment]
> Thank you for reporting this issue.
> Yes. We will check the annotations again & add missing labels in the future.
> For convenience, we plan to keep the current version (v1.0) annotation files unchanged. The updated version will have a different suffix (for example, v2.0).
> Thanks again.

cool. awaiting for that.

**Comment by ZYX-MLer** [comment]
Has version 2 been released? Is there a specific plan?
