### ISSUE TITLE
Could you supply me with Zoomnet and Pretrain Model 

### ISSUE THREAD

**Issue by lingtengqiu** [jin-s13/COCO-WholeBody#7]
I am very interesting in your work and want to follow your work. I don't Know whether you could provide zoomnet and its weights to me.

Hope for your reply.
Best 
Qiu

**Comment by zimenglan-sysu-512** [comment]
+1

**Comment by jin-s13** [comment]
Thanks for your interest in our work!
We plan to support COCO-WholeBody dataset in our newly released code-base [MMPose](https://github.com/open-mmlab/mmpose) this month (Sep, 2020), see [Iteration Plan](https://github.com/open-mmlab/mmpose/issues/118).

**Comment by jin-s13** [comment]
Hi, we have already supported this COCO-WholeBody dataset in MMPose. 
We also provide a much stronger baseline, see #3 .
