### ISSUE TITLE
val annotations quesiton 

### ISSUE THREAD

**Issue by lingtengqiu** [jin-s13/COCO-WholeBody#8]
I saw your annotations for validation is not very clear.
Why keypoints hand_left have confidence like(0.731)? is your results of results?

**Comment by lingtengqiu** [comment]
like following format:
'lefthand_kpts': [237.0, 426.0, 0.10405432432889938, 245.0, 428.0, 0.20745894312858582, 253.0, 430.0, 0.20745894312858582, 261.0, 433.0, 0.5343613624572754, 269.0, 438.0, 0.2143213450908661, 265.0, 429.0, 0.12357126176357269, 270.0, 433.0, 0.26612094044685364, 269.0, 439.0, 0.09291676431894302, 265.0, 445.0, 0.1144329234957695, 264.0, 427.0, 0.04132022708654404, 269.0, 438.0, 0.14125224947929382, 265.0, 445.0, 0.12546022236347198, 260.0, 446.0, 0.1301765739917755, 261.0, 431.0, 0.03911404311656952, 269.0, 438.0, 0.05325932428240776, 263.0, 445.0, 0.0727347582578659, 260.0, 446.0, 0.09616264700889587, 262.0, 426.0, 0.02422112599015236, 262.0, 446.0, 0.05307695269584656, 259.0, 447.0, 0.10021205991506577, 256.0, 449.0, 0.16766609251499176], 'righthand_kpts': [308.0, 239.0, 0.1408521831035614, 321.0, 226.5, 0.02196568436920643, 334.0, 214.0, 0.02196568436920643, 354.0, 211.0, 0.10082424432039261, 365.0, 206.0, 0.7382210493087769, 346.0, 209.0, 0.36809757351875305, 364.0, 214.0, 0.18089689314365387, 355.0, 209.0, 0.1661667376756668, 370.0, 226.0, 0.0630379319190979, 342.0, 214.0, 0.20839764177799225, 364.0, 216.0, 0.3880220949649811, 368.0, 226.0, 0.26579514145851135, 374.0, 236.0, 0.2594422996044159, 338.0, 218.0, 0.4262842833995819, 356.0, 220.0, 0.6470030546188354, 364.0, 227.0, 0.3695657551288605, 372.0, 237.0, 0.14602071046829224, 335.0, 227.0, 0.425717294216156, 347.0, 229.0, 0.479814738035202, 356.0, 232.0, 0.3711409270763397, 364.0, 234.0, 0.39777901768684387]

**Comment by jin-s13** [comment]
The result is first pre-annotated by machine. If the machine results are correct, the annotators will not change them. The confidence score is also kept as it is. You can simply ignore it, and regard them as 'visible' (=1), if the confidence score > 0.
Also see #5 .
