### ISSUE TITLE
Is there training code to reproduce your experiment? Thank you for checking my issue!

### ISSUE THREAD

**Issue by yanghu819** [jin-s13/COCO-WholeBody#9]

**Comment by jin-s13** [comment]
The training codes will be released in [MMPose](https://github.com/open-mmlab/mmpose). 
Now, MMPose has already supported the top-down baselines.

**Comment by yanghu819** [comment]
I see， thank you

Jas <notifications@github.com> 于2020年10月8日周四 下午3:01写道：
